config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/index' #chạy khi localhost với đường dẫn 172.0.1:3000/home/index
  get 'home/about'

  root 'friends#index' 
  # root 'home#index'#chạy ngay khi vào localhost không có đường dẫn =>127.0.1:3000
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
        has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [ :show, :edit ,:update, :destroy ]
  # before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]   # phải đăng nhập ngoại trừ những mục except
  before_action :correct_user, only: [:edit, :update, :destroy]   # phải đăng nhập ngoại trừ những mục except
  
  
  # GET /friends or /friends.json
  def index
    @friends = Friend.all 
   
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend =current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #! check athur
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend"  if @friend.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= stylesheet_link_tag "friends" %>
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <!-- <%= form.label :first_name %> -->
    <%= form.text_field :first_name , class:"form-control",placeholder:"First Name"%>
  </div>

  <div class="field form-group">
    <!-- <%= form.label :last_name %> -->
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <!-- <%= form.label :email %> -->
    <%= form.text_field :email, class:"form-control",placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <!-- <%= form.label :phone %> -->
    <%= form.text_field :phone , class:"form-control",placeholder:"Phone"%>
  </div>

  <div class="field form-group">
    <!-- <%= form.label :address %> -->
    <%= form.text_field :address , class:"form-control",placeholder:"Address"%>
  </div>
  <div class="field form-group">
    <!-- <%= form.label :address %> -->
    <%= form.number_field :user_id , class:"form-control", value: current_user.id, id: :friend_user_id, type: :hidden %>
  </div>
  <!-- <%= current_user.id %>   lay id nguoi dung dang nhap hien tai -->

  <div class="actions">
    <%= form.submit  class:'btn btn-secondary'%>
  </div>

<% end %>

app/views/friends/edit.html.erb
<div class="card">
    <div class="card-header">
        <h1>Editing Friend</h1>
    </div>
    <div class="card-body">
        <%= render 'form' , friend: @friend %>
            </br>
        <%= link_to 'Show' , @friend , class:"btn btn-secondary" %> |
        <td><%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'Back' , friends_path, class:"btn btn-dark" %>
    
    </div>
    
</div>

app/views/friends/index.html.erb
<%= stylesheet_link_tag "friends" %>
<% if user_signed_in? %>
  <table class="table table-bordered table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th>User Id</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
      <% if friend.user == current_user %> 
      <!-- chỉ hiện thị friends của user đó. không hiển thị cả user sing in -->
        <tr>
          <td> <%=  link_to friend.first_name+' '+friend.last_name , friend   %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.address %></td>
          <td><%= friend.user_id %></td>

          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path , class:"btn btn-secondary"%>
<% else %>
<h1> Hello Your</h1>
<p>Wellcome rails. You have to sing in</p>
<%end %>

app/views/friends/new.html.erb
    <div class="card">
        <div class="card-header">
            <h1> Add New Friend</h1>
        </div>
        <div class="card-body">
            <%= render 'form', friend: @friend %></br>
            <%= link_to 'Back', friends_path  , class:"btn btn-info"%>
        </div>
        
    </div>
    

app/views/friends/show.html.erb
</br>
<div class="jumbotron">
  <h1 class="display-4">Hello, 
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
 <p class="lead">
   <%= @friend.email %>   |
   <%= @friend.phone %>   |
   <%= @friend.address %>
  </p>
<br/>
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-success"%> |
  <%= link_to 'Back', friends_path  , class:"btn btn-success"%>
</div>


<!-- <p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @friend.address %>
</p> -->

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Friends ", home_index_path,class:"navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">Friend App</a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            
            <li class="nav-item">
              <%= link_to "Friends List" , friends_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About Us" , home_about_path, class:"nav-link" %>
            
            </li>

            <% if user_signed_in?%> 
              <!--! xác minh người dùng đã đăng nhập hay chưa -->
              <li class="nav-item">
                <%= link_to "Add Friends" , new_friend_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sing Out" ,   destroy_user_session_path, class:"nav-link", method: :delete %>
              
              </li>
              <li class="nav-item">
                <%= link_to "Edit Profile" , edit_user_registration_path, class:"nav-link" %>
              
              </li>

            <% else%> 

              <li class="nav-item">
                <%= link_to "Sing Up" , new_user_registration_path, class:"nav-link" %>
              
              </li>
              <li class="nav-item">
                <%= link_to "Sing In" , new_user_session_path, class:"nav-link" %>
              
              </li>
            <% end %>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
 

app/views/home/about.html.erb
<h1>About us...</h1>

app/views/home/index.html.erb
<h1> Hello Your</h1>
<p>Wellcome rails</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Myfriend</title>
  </head>
  <body>
    <%= render 'home/header'%>
  </br>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>
    </br>
      <%= yield %>
    </div>
   

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>